# Site settings
title: "Joonseo Kym's Resume"
description: "The resume of Joonseo Kym, an undergraduate student at KAIST."
url: "https://joonseokym.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar: "true"
resume_name: "Joonseo Kym"
resume_title: "Undergraduate Student<br>@ Dep. of Mechanical Engineering, KAIST"

# used for the contact button in _layouts/resume.html
resume_contact_email: "joonseo@kaist.ac.kr"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone: "(+82)10-8025-4547"
resume_contact_address: "Daejeon, South Korea"

resume_header_contact_info: "Daejeon, South Korea • (+82)10-8025-4547 • joonseo@kaist.ac.kr"
display_header_contact_info: "false"

resume_header_intro: "<p>
  <strong>Undergraduate Researcher at KAIST, Department of Mechanical Engineering.</strong><br>
  I am dedicated to advancing Human-Machine Interfaces (HMI) through novel sensing technologies and robotics. My current research focuses on developing optimal pneumatic mechanomyography (pMMG) sensors for precise muscle activation analysis, aiming to innovate wearable technology and rehabilitation systems.
  <br><br>
  I possess a comprehensive engineering skillset bridging hardware and software: from mechanical design (CAD) and sensor fabrication to real-time data acquisition and signal processing using Python. With a solid foundation in system modeling and control theory, I am eager to contribute to cutting-edge research that integrates mechanical ingenuity with intelligent systems.
</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work: "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience: true
resume_section_education: true
resume_section_projects: true
resume_section_skills: true
resume_section_patents: true
resume_section_recognition: true
resume_section_links: true
resume_section_associations: true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url: "https://github.com/joonseokym"
  # resume_twitter_url: "http://twitter.com/jglovier"
  # resume_dribbble_url: "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url: "https://www.linkedin.com/in/joonseokym/"
  resume_instagram_url: "https://www.instagram.com/ssemiwest/"
  # resume_website_url: "http://joelglovier.com"
  # resume_medium_url: "https://medium.com/@jglovier"
resume_print_social_links: true

# Design settings
resume_theme: default
# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
